### Send a letter 
POST http://localhost:3000/letters
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YWU5OThiNi0xMzlhLTRhZTQtYTRhYi0xOTUzMDhkYmMzZjMiLCJlbWFpbCI6ImJydW5vdGVzdDEzNEBleGFtcGxlLmNvbSIsImlhdCI6MTc2NzIwNjk5NX0.e9TB7IRa9AbfKGlqCozW8cJKO3o0MHb3q3XJUxDDCxQ


{
    "toId": "b798bbea-5eaf-45ed-a858-df5cba0746a3",
    "fromId": "60c067fc-a85a-4d2b-a6f2-aa21312690fe",
    "letter": "Apenas um testesssssss"
}

### Get all letters with pagination
GET http://localhost:3000/letters/
